apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.backend.appEnv | quote }}
  WELCOME_MESSAGE: {{ .Values.backend.welcomeMessage | quote }}
  LOG_LEVEL: "info"
